### ISSUE TITLE
Block Height Tracker

### ISSUE THREAD

**Issue by maaatttt** [ubiq/tars-discord#33]
Request to explore additional commands for TARS bot in Ubiq Discord in regards to block height
e.g; 

- remaining blocks / estimated time remaining until mining reward reductions
- remaining blocks / estimated time remaining for Escher token airdrop claims
- remaining blocks / estimated time remaining for UIP votes
- remaining blocks / estimated time remaining to upgrade clients in regards to hard forks

**Comment by jyap808** [comment]
Added to Dikembe bot.

Thanks for the suggestion!
