### ISSUE TITLE
Add !dojo & !dex commands to list of Tars commands in discord

### ISSUE THREAD

**Issue by krislester123** [ubiq/tars-discord#45]
Request to please add the following commands to Tars (would be useful if it can be done without discord embeds)

!dojo

Please read the following guides when using the Shinobi dex:

- Introduction and making trades: https://blog.ubiqsmart.com/the-ubiq-dex-introducing-shinobi-5433adecc5e3
- Using Sparrow: https://blog.ubiqsmart.com/the-ubiq-dex-using-sparrow-96bb604a1c89
- Liquidity Pools: https://blog.ubiqsmart.com/the-ubiq-dex-liquidity-pools-6b1b1982c30a

Additional guides can be found at: https://ubiq.ninja/dojo

!dex

You can access Shinobi by visiting: https://shinobi.ubiq.ninja/

Information can be found at: https://info.ubiq.ninja/

If possible also a total liquidity $$ and total pools XX

**Comment by jyap808** [comment]
Closed by https://github.com/ubiq/tars-discord/commit/96ecb2c49b83169fec220a2bb4bb6698a1f0be73
